
const CHANNELS = {
    POST_ADMIN_CREDENTIALS:'POST_ADMIN_CREDENTIALS',
    GET_ADMIN_CREDENTIALS:'GET_ADMIN_CREDENTIALS',
    POST_DEMO_CREDENTIALS:'POST_DEMO_CREDENTIALS',
    GET_DEMO_CREDENTIALS:'GET_DEMO_CREDENTIALS',
    GET_BROWSERSTACK_AUTOMATE_SESSION:'GET_BROWSERSTACK_AUTOMATE_SESSION',
    GET_BROWSERSTACK_AUTOMATE_PARSED_TEXT_LOGS:'GET_BROWSERSTACK_AUTOMATE_PARSED_TEXT_LOGS',
    GET_BROWSERSTACK_AUTOMATE_PARSED_SESSION_LOGS:'GET_BROWSERSTACK_AUTOMATE_PARSED_SESSION_LOGS',
    BROWSERSTACK_START_SESSION:'BROWSERSTACK_START_SESSION'
}

export default CHANNELS