
const CHANNELS = {
    POST_ADMIN_CREDENTIALS:'POST_ADMIN_CREDENTIALS',
    GET_ADMIN_CREDENTIALS:'GET_ADMIN_CREDENTIALS',
    POST_DEMO_CREDENTIALS:'POST_DEMO_CREDENTIALS',
    GET_DEMO_CREDENTIALS:'GET_DEMO_CREDENTIALS',
    GET_BROWSERSTACK_AUTOMATE_SESSION:'GET_BROWSERSTACK_AUTOMATE_SESSION',
    GET_BROWSERSTACK_AUTOMATE_PARSED_TEXT_LOGS:'GET_BROWSERSTACK_AUTOMATE_PARSED_TEXT_LOGS',
    BROWSERSTACK_START_SESSION:'BROWSERSTACK_START_SESSION',
    BROWSERSTACK_STOP_SESSION:'BROWSERSTACK_STOP_SESSION',
    BROWSERSTACK_EXECUTE_SESSION_COMMAND:'BROWSERSTACK_EXECUTE_SESSION_COMMAND',
    ELECTRON_OPEN_URL:'ELECTRON_OPEN_URL',
    GET_BROWSERSTACK_AUTOMATE_PARSED_SESSION_LOGS:'GET_BROWSERSTACK_AUTOMATE_PARSED_SESSION_LOGS',
    GET_BROWSERSTACK_AUTOMATE_PARSED_SELENIUM_LOGS:'GET_BROWSERSTACK_AUTOMATE_PARSED_SELENIUM_LOGS',
    GET_BROWSERSTACK_AUTOMATE_SELENIUM_LOGS: 'GET /automate/sessions/seleniumLogs',
    GET_BROWSERSTACK_AUTOMATE_HAR_LOGS: 'GET /automate/sessions/harLogs',
    GET_BROWSERSTACK_SCANNER_AUTOMATE_SESSION_IDS: 'GET_BROWSERSTACK_SCANNER_AUTOMATE_SESSION_IDS'
}

export default CHANNELS