import { app, BrowserWindow, protocol, net, ipcMain } from 'electron';
import path from 'path';
import url from 'url';
import CHANNELS from './constants/ipc-channels';
import { getBrowserStackAdminCredentials, getBrowserStackDemoCredentials, setBrowserStackAdminCredentials, setBrowserStackDemoCredentials } from './channelHandlers/credentials-api';
import getStorage from './storage';
import StorageKeys from './constants/storage-keys';
import CONFIG from './constants/config';

import { mkdirSync } from 'fs'
import { executeCommand, getAutomateSessionDetails, getParsedAutomateTextLogs, startBrowserStackSession, stopBrowserStackSession, getAutomateParsedSeleniumLogs, getAutomateParsedSessionLogs, } from './channelHandlers/browserstack-api';
import { openExternalUrl } from './channelHandlers/electron-api';

import { get } from 'http';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

protocol.registerSchemesAsPrivileged([
  { scheme: 'static', privileges: { secure: true, standard: true, supportFetchAPI: true } }
]);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  mkdirSync(`${app.getPath('userData')}/debugging-hub`, { recursive: true })
  const storage = getStorage();
  try {
    const adminCreds = await storage.get<BrowserStackCredentials>(StorageKeys.bstackAdminCredentials);
    const demoCreds = await storage.get<BrowserStackCredentials>(StorageKeys.bstackDemoCredentials);
    CONFIG.adminUsername = adminCreds.username
    CONFIG.adminAccessKey = adminCreds.accessKey
    CONFIG.demoUsername = demoCreds.username
    CONFIG.demoAccessKey = demoCreds.accessKey
  } catch (err) {
    console.error(err)
  }
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.whenReady().then(() => {
  // Customize protocol to handle static resource.
  protocol.handle('static', (request) => {
    const filePath = request.url.slice('static://'.length)
    console.log(url.pathToFileURL(path.join(__dirname, filePath)).toString())
    return net.fetch(url.pathToFileURL(path.join(__dirname, filePath)).toString())
  });

  // IPC Handlers
  ipcMain.handle(CHANNELS.POST_ADMIN_CREDENTIALS, (_, username, accessKey, _rev) => setBrowserStackAdminCredentials(username, accessKey, _rev));
  ipcMain.handle(CHANNELS.GET_ADMIN_CREDENTIALS, getBrowserStackAdminCredentials);
  ipcMain.handle(CHANNELS.POST_DEMO_CREDENTIALS, (_, username, accessKey, _rev) => setBrowserStackDemoCredentials(username, accessKey, _rev));
  ipcMain.handle(CHANNELS.GET_DEMO_CREDENTIALS, getBrowserStackDemoCredentials);
  ipcMain.handle(CHANNELS.GET_BROWSERSTACK_AUTOMATE_SESSION, (_, id) => getAutomateSessionDetails(id))
  ipcMain.handle(CHANNELS.GET_BROWSERSTACK_AUTOMATE_PARSED_TEXT_LOGS, (_, session) => getParsedAutomateTextLogs(session))
  ipcMain.handle(CHANNELS.GET_BROWSERSTACK_AUTOMATE_PARSED_SESSION_LOGS, (_, session) => getAutomateParsedSessionLogs(session))
  ipcMain.handle(CHANNELS.GET_BROWSERSTACK_AUTOMATE_PARSED_SELENIUM_LOGS, (_, session) => getAutomateParsedSeleniumLogs(session))
  ipcMain.handle(CHANNELS.BROWSERSTACK_START_SESSION, (_, options) => startBrowserStackSession(options))
  ipcMain.handle(CHANNELS.BROWSERSTACK_STOP_SESSION, (_, options) => stopBrowserStackSession(options))
  ipcMain.handle(CHANNELS.BROWSERSTACK_EXECUTE_SESSION_COMMAND, (_, options) => executeCommand(options))
  ipcMain.handle(CHANNELS.ELECTRON_OPEN_URL, (_, url) => openExternalUrl(url))
});
// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
